import { PoDItem } from '../types/podValidation';

// SVG Signatures and Proof Photo placeholders (SVG encoded Data URIs)
const MOCK_SIGNATURE_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="150" viewBox="0 0 300 150"><rect width="100%" height="100%" fill="%230f172a"/><path d="M 30 90 Q 70 20, 110 80 T 170 60 T 230 100 Q 260 40, 280 70" stroke="%23818cf8" stroke-width="4" fill="none" stroke-linecap="round"/><circle cx="280" cy="70" r="3" fill="%23818cf8"/><text x="20" y="135" fill="%2364748b" font-size="12" font-family="monospace">CERTIFIED SIGNATURE #POD-8891</text></svg>`;

const MOCK_DOOR_PHOTO_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="150" viewBox="0 0 300 150"><rect width="100%" height="100%" fill="%231e293b"/><rect x="80" y="30" width="70" height="100" fill="%23334155" stroke="%23475569" stroke-width="2"/><circle cx="140" cy="80" r="4" fill="%23f59e0b"/><rect x="180" y="50" width="80" height="60" fill="%230f172a" stroke="%23475569"/><text x="190" y="85" fill="%2310b981" font-size="10" font-family="sans-serif">DEPOT PORTE</text><text x="20" y="135" fill="%2364748b" font-size="10" font-family="monospace">PHOTO DEPOT #LT-90412</text></svg>`;

const MOCK_CLOSED_DOOR_ANOMALY_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="150" viewBox="0 0 300 150"><rect width="100%" height="100%" fill="%231e1b4b"/><rect x="90" y="25" width="80" height="110" fill="%23431407" stroke="%23ef4444" stroke-width="3"/><circle cx="105" cy="80" r="5" fill="%23991b1b"/><text x="100" y="70" fill="%23fca5a5" font-size="12" font-weight="bold" font-family="sans-serif">FERMÉ</text><text x="20" y="140" fill="%23f87171" font-size="10" font-family="monospace">ECHEC: PORTE FERMEE / ABSENT</text></svg>`;

export const MOCK_POD_ITEMS: PoDItem[] = [
  {
    id: 'pod-101',
    tracking_number: 'LT-INV-84920',
    client_id: 'cli-orange',
    client_name: 'Orange Guinée',
    client_code: 'OGN',
    recipient_name: 'Sory Camara',
    recipient_phone: '+224 622 90 11 00',
    recipient_address: 'Immeuble BCRG, 3ème Étage, Kaloum',
    operation_type: 'MASS_INVOICE_DISTRIBUTION',
    item_type: 'invoice',
    agent_id: 'agent-101',
    agent_name: 'Mamadou Diallo',
    zone_name: 'Kaloum Centre-Ville',
    delivery_timestamp: 'Aujourd\'hui à 09:10',
    status: 'PENDING',
    delivery_method: 'REMISE_DIRECTE',
    proof_type: 'signature',
    proof_image_url: MOCK_SIGNATURE_SVG,
    gps_lat: 9.5105,
    gps_lng: -13.7118,
    expected_lat: 9.5104,
    expected_lng: -13.7119,
    gps_distance_diff_meters: 12
  },
  {
    id: 'pod-102',
    tracking_number: 'LT-PAR-90412',
    client_id: 'cli-ba',
    client_name: 'Banque Atlantique',
    client_code: 'BAT',
    recipient_name: 'Mariama Sylla',
    recipient_phone: '+224 628 44 55 66',
    recipient_address: 'Villa 14, Almamya Sandervalia',
    operation_type: 'PARCEL_DELIVERY_COD',
    item_type: 'parcel_cod',
    cod_amount: 1250000,
    agent_id: 'agent-101',
    agent_name: 'Mamadou Diallo',
    zone_name: 'Kaloum Centre-Ville',
    delivery_timestamp: 'Aujourd\'hui à 10:25',
    status: 'APPROVED',
    delivery_method: 'TIERS_MANDATAIRE',
    proof_type: 'signature',
    proof_image_url: MOCK_SIGNATURE_SVG,
    proxy_info: {
      name: 'Ibrahima Sylla',
      relation: 'Frère (Tiers Mandataire)',
      cni_number: 'CNI-GN-2024-88419',
      phone: '+224 621 33 22 11'
    },
    gps_lat: 9.5078,
    gps_lng: -13.7145,
    expected_lat: 9.5079,
    expected_lng: -13.7146,
    gps_distance_diff_meters: 18,
    audited_by: 'Yves Touré (Dispatcher)',
    audited_at: 'Aujourd\'hui à 11:00'
  },
  {
    id: 'pod-103',
    tracking_number: 'LT-CONF-1092',
    client_id: 'cli-edm',
    client_name: 'Électricité De Guinée (EDG)',
    client_code: 'EDG',
    recipient_name: 'Ousmane Barry',
    recipient_phone: '+224 620 12 34 56',
    recipient_address: 'Ministère des Finances, Boulbinet',
    operation_type: 'CONFIDENTIAL_MAIL',
    item_type: 'confidential_mail',
    agent_id: 'agent-101',
    agent_name: 'Mamadou Diallo',
    zone_name: 'Kaloum Centre-Ville',
    delivery_timestamp: 'Aujourd\'hui à 11:40',
    status: 'PENDING',
    delivery_method: 'DEPOT_BOITE_AUX_LETTRES',
    proof_type: 'photo',
    proof_image_url: MOCK_DOOR_PHOTO_SVG,
    gps_lat: 9.5042,
    gps_lng: -13.7179,
    expected_lat: 9.5040,
    expected_lng: -13.7182,
    gps_distance_diff_meters: 35
  },
  {
    id: 'pod-104',
    tracking_number: 'LT-PAR-33109',
    client_id: 'cli-sodeci',
    client_name: 'SODECI Côte d\'Ivoire',
    client_code: 'SDC',
    recipient_name: 'Moussa Ndiaye',
    recipient_phone: '+221 77 900 11 22',
    recipient_address: 'Marché Tilène, Rue 12 x 14, Medina',
    operation_type: 'PARCEL_DELIVERY_COD',
    item_type: 'package',
    cod_amount: 150000,
    agent_id: 'agent-103',
    agent_name: 'Ousmane Sow',
    zone_name: 'Dakar Plateau & Medina',
    delivery_timestamp: 'Hier à 16:30',
    status: 'ANOMALY',
    delivery_method: 'REMISE_DIRECTE',
    proof_type: 'photo',
    anomaly_reason: 'CLIENT_ABSENT',
    anomaly_notes: 'Magasin fermé après 3 appels téléphoniques sans réponse. Photo de la devanture jointe.',
    anomaly_photo_url: MOCK_CLOSED_DOOR_ANOMALY_SVG,
    gps_lat: 14.6891,
    gps_lng: -17.4478,
    expected_lat: 14.6890,
    expected_lng: -17.4475,
    gps_distance_diff_meters: 22
  },
  {
    id: 'pod-105',
    tracking_number: 'LT-INV-50931',
    client_id: 'cli-mtn',
    client_name: 'MTN Business',
    client_code: 'MTN',
    recipient_name: 'Cabinet Dr Kassi',
    recipient_phone: '+225 07 11 22 33 44',
    recipient_address: 'Pharmacie Saint Jean, Cocody Centre',
    operation_type: 'MASS_INVOICE_DISTRIBUTION',
    item_type: 'invoice',
    agent_id: 'agent-102',
    agent_name: 'Koffi Jean-Baptiste',
    zone_name: 'Cocody & Riviera',
    delivery_timestamp: 'Aujourd\'hui à 09:45',
    status: 'APPROVED',
    delivery_method: 'OTP_SMS',
    proof_type: 'otp',
    otp_code_verified: '7492',
    gps_lat: 5.3567,
    gps_lng: -3.9812,
    expected_lat: 5.3566,
    expected_lng: -3.9810,
    gps_distance_diff_meters: 15,
    audited_by: 'Yves Touré',
    audited_at: 'Aujourd\'hui à 10:15'
  },
  {
    id: 'pod-106',
    tracking_number: 'LT-INV-99012',
    client_id: 'cli-cie',
    client_name: 'CIE Électricité CI',
    client_code: 'CIE',
    recipient_name: 'Société SOTRA Niangon',
    recipient_phone: '+225 05 99 88 77',
    recipient_address: 'Zone Industrielle Yopougon, Lot 45',
    operation_type: 'MASS_INVOICE_DISTRIBUTION',
    item_type: 'invoice',
    agent_id: 'agent-106',
    agent_name: 'Awa Koné',
    zone_name: 'Yopougon Industrial Zone',
    delivery_timestamp: 'Hier à 14:10',
    status: 'ANOMALY',
    delivery_method: 'REMISE_DIRECTE',
    proof_type: 'photo',
    anomaly_reason: 'CLIENT_DEMENAGE',
    anomaly_notes: 'L\'entreprise a déménagé vers Treichville le mois dernier selon le vigile du site.',
    anomaly_photo_url: MOCK_CLOSED_DOOR_ANOMALY_SVG,
    gps_lat: 5.3340,
    gps_lng: -4.0810,
    expected_lat: 5.3380,
    expected_lng: -4.0850,
    gps_distance_diff_meters: 520 // ECART GPS IMPORTANT
  }
];
