import { Mission, MissionKpis } from '@/types/mission';

export const MOCK_MISSIONS_KPIS: MissionKpis = {
  total: 14500,
  active: 3800,
  completed: 9850,
  delayed: 142,
  failed: 48,
  suspended: 18
};

export const MOCK_DETAILED_MISSIONS: Mission[] = [
  {
    id: 'mis-001',
    mission_number: 'MIS-2026-0089',
    organization_id: 'tenant-101',
    client_id: 'cli-cie',
    client_name: 'CIE Électricité',
    client_code: 'CIE',
    campaign_id: 'camp-1',
    campaign_reference: 'CAMP-CIE-2026-08',
    campaign_name: 'Distribution Factures CIE Électricité Août 2026',
    batch_id: 'batch-101',
    batch_number: 'LOT-ABJ-COC-01',
    recipient_name: 'Société Ivoirienne de Banque (SIB)',
    recipient_phone: '+225 07 08 12 34 56',
    recipient_email: 'courrier@sib.ci',
    address_raw: 'Boulevard Latrille Villa 14',
    district_name: 'Riviera 2',
    sector_name: 'Cocody',
    city_name: 'Abidjan',
    landmark_description: 'En face de la pharmacie St-Jean, porte 12',
    latitude: 5.3610,
    longitude: -3.9740,
    item_type: 'invoice',
    operation_type: 'MASS_INVOICE_DISTRIBUTION',
    description: 'Distribution facture moyenne tension SIB Agence Riviera.',
    priority: 'URGENTE',
    sla_hours: 24,
    due_date: '2026-08-08',
    cod_amount: 0,
    payment_status: 'NO_PAYMENT_REQUIRED',
    assigned_agent_id: 'a1',
    assigned_agent_name: 'Kouassi Jean-Marc',
    assigned_agent_phone: '+225 07 08 12 34 56',
    team_leader_name: 'Traoré Bakary (Chef Zone)',
    supervisor_name: 'Yves Touré (Dispatcher)',
    status: 'EN_COURS',
    start_time: '2026-08-06 08:30',
    execution_duration_min: 25,
    result_summary: 'Agent en route vers l\'adresse destinataire',
    created_at: '2026-08-06 07:30',
    updated_at: '2026-08-06 08:30',
    history: [
      {
        id: 'h-1',
        mission_id: 'mis-001',
        previous_status: 'CREEE',
        new_status: 'AFFECTEE',
        user_name: 'Yves Touré (Dispatcher)',
        action_title: 'Affectation de la mission',
        comment: 'Mission affectée à Kouassi Jean-Marc',
        created_at: '2026-08-06 08:00'
      },
      {
        id: 'h-2',
        mission_id: 'mis-001',
        previous_status: 'AFFECTEE',
        new_status: 'ACCEPTEE',
        user_name: 'Kouassi Jean-Marc',
        action_title: 'Acceptation Agent',
        comment: 'Mission acceptée sur PWA mobile',
        created_at: '2026-08-06 08:15'
      },
      {
        id: 'h-3',
        mission_id: 'mis-001',
        previous_status: 'ACCEPTEE',
        new_status: 'EN_COURS',
        user_name: 'Kouassi Jean-Marc',
        action_title: 'Démarrage Tournée',
        comment: 'Top départ livraison GPS',
        created_at: '2026-08-06 08:30'
      }
    ],
    incidents: [],
    documents: [
      {
        id: 'doc-1',
        mission_id: 'mis-001',
        file_name: 'Facture_CIE_AUG2026_SIB.pdf',
        file_type: 'INVOICE',
        file_size_bytes: 425000,
        storage_path: 'invoices/2026/08/Facture_CIE_AUG2026_SIB.pdf',
        public_url: 'https://demo.supabase.co/storage/v1/object/public/documents/Facture_CIE_AUG2026_SIB.pdf',
        uploaded_by_name: 'CIE Import System',
        created_at: '2026-08-06 07:30'
      }
    ],
    comments: [
      {
        id: 'com-1',
        mission_id: 'mis-001',
        author_role: 'DISPATCHER',
        author_name: 'Yves Touré',
        comment_text: 'Remise au secrétariat de direction recommandé si M. le Directeur est absent.',
        created_at: '2026-08-06 08:05'
      }
    ]
  },
  {
    id: 'mis-002',
    mission_number: 'MIS-2026-0090',
    organization_id: 'tenant-101',
    client_id: 'cli-sodeci',
    client_name: 'SODECI Eau',
    client_code: 'SOD',
    campaign_id: 'camp-2',
    campaign_reference: 'CAMP-SODECI-2026-08',
    campaign_name: 'Campagne Relevés d\'Eau SODECI Abidjan',
    batch_id: 'batch-102',
    batch_number: 'LOT-ABJ-YOP-02',
    recipient_name: 'Sylla Fatoumata',
    recipient_phone: '+225 05 04 99 88 77',
    recipient_email: 'fatou.sylla@gmail.com',
    address_raw: 'Angré Djibi Villa 88',
    district_name: 'Djibi',
    sector_name: 'Yopougon',
    city_name: 'Abidjan',
    landmark_description: 'Près du château d\'eau, porte 12',
    latitude: 5.3580,
    longitude: -3.9710,
    item_type: 'package',
    operation_type: 'PARCEL_DELIVERY_COD',
    description: 'Livraison colis e-commerce avec encaissement COD de 12 500 FCFA.',
    priority: 'HAUTE',
    sla_hours: 48,
    due_date: '2026-08-09',
    cod_amount: 12500,
    payment_status: 'PENDING_COD',
    assigned_agent_id: 'a2',
    assigned_agent_name: 'Diallo Mamadou',
    assigned_agent_phone: '+225 05 04 99 88 77',
    team_leader_name: 'Coulibaly Dramane',
    supervisor_name: 'Yves Touré',
    status: 'ECHOUEE',
    start_time: '2026-08-06 09:10',
    end_time: '2026-08-06 09:45',
    execution_duration_min: 35,
    result_summary: 'Échec livraison - Téléphone injoignable',
    failure_reason: 'phone_unreachable',
    failure_notes: '3 tentatives d\'appel sans réponse. Repère visuel vérifié.',
    created_at: '2026-08-06 08:15',
    updated_at: '2026-08-06 09:45',
    history: [
      {
        id: 'h-21',
        mission_id: 'mis-002',
        previous_status: 'EN_COURS',
        new_status: 'ECHOUEE',
        user_name: 'Diallo Mamadou',
        action_title: 'Déclaration Échec Delivery',
        comment: 'Destinataire injoignable par téléphone',
        created_at: '2026-08-06 09:45'
      }
    ],
    incidents: [
      {
        id: 'inc-1',
        mission_id: 'mis-002',
        incident_type: 'PHONE_UNREACHABLE',
        severity: 'MEDIUM',
        reported_by_name: 'Diallo Mamadou',
        description: 'Le destinataire ne décroche pas après 3 tentatives.',
        status: 'OPEN',
        created_at: '2026-08-06 09:45'
      }
    ],
    documents: [],
    comments: []
  },
  {
    id: 'mis-003',
    mission_number: 'MIS-2026-0091',
    organization_id: 'tenant-101',
    client_id: 'cli-bdm',
    client_name: 'Banque de Développement du Mali (BDM)',
    client_code: 'BDM',
    campaign_id: 'camp-3',
    campaign_reference: 'CAMP-BAM-2026-004',
    campaign_name: 'Distribution Relevés Bancaires BDM Bamako',
    batch_id: 'batch-103',
    batch_number: 'LOT-BMK-COU-01',
    recipient_name: 'Cabinet Médical de l\'Union',
    recipient_phone: '+223 70 12 34 56',
    address_raw: 'Bamako Coura Rue 114 Immeuble Keita',
    district_name: 'Coura',
    sector_name: 'Bamako Coura',
    city_name: 'Bamako',
    landmark_description: 'A côté de la pharmacie Populaire',
    latitude: 12.6365,
    longitude: -8.0010,
    item_type: 'registered_mail',
    operation_type: 'CONFIDENTIAL_MAIL',
    description: 'Remise pli recommandé confidentiel avec décharge et CNI.',
    priority: 'NORMALE',
    sla_hours: 12,
    due_date: '2026-08-06',
    cod_amount: 0,
    payment_status: 'NO_PAYMENT_REQUIRED',
    assigned_agent_id: 'a3',
    assigned_agent_name: 'Traoré Bakary',
    assigned_agent_phone: '+223 70 12 34 56',
    team_leader_name: 'Traoré Bakary',
    supervisor_name: 'Yves Touré',
    status: 'VALIDEE',
    start_time: '2026-08-06 08:00',
    end_time: '2026-08-06 08:20',
    execution_duration_min: 20,
    result_summary: 'Livraison certifiée avec Signature & CNI Proxy',
    pod_id: 'pod-991',
    created_at: '2026-08-05 09:00',
    updated_at: '2026-08-06 08:25',
    history: [
      {
        id: 'h-31',
        mission_id: 'mis-003',
        previous_status: 'TERMINEE',
        new_status: 'VALIDEE',
        user_name: 'Yves Touré (Dispatcher)',
        action_title: 'Audit & Certification PoD',
        comment: 'Preuve POD certifiée conforme',
        created_at: '2026-08-06 08:25'
      }
    ],
    incidents: [],
    documents: [],
    comments: []
  }
];
